/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_arturo_cartoonifier_CameraPreview */

#ifndef _Included_com_example_arturo_cartoonifier_CameraPreview
#define _Included_com_example_arturo_cartoonifier_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_arturo_cartoonifier_CameraPreview
 * Method:    NativeCartoon
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_arturo_cartoonifier_NativeCartoon_processImage
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
